Add spec file for gtk

diff --git a/patches/glib/glib-1.2.8-configure.patch b/patches/glib/glib-1.2.8-configure.patch
--- a/patches/glib/glib-1.2.8-configure.patch
+++ b/patches/glib/glib-1.2.8-configure.patch
@@ -850,3 +850,99 @@ diff -rupN glib-1.2.8.orig/tests/Makefile.am glib-1.2.8/tests/Makefile.am
  
  EXTRA_DIST = \
  	makefile.msc \
+diff -rupN glib-1.2.8.orig/glib.m4 glib-1.2.8/glib.m4
+--- glib-1.2.8.orig/glib.m4	2023-03-26 07:24:35.357578925 +0200
++++ glib-1.2.8/glib.m4	2023-03-26 07:28:56.241251154 +0200
+@@ -5,7 +5,7 @@
+ dnl Test for GLIB, and define GLIB_CFLAGS and GLIB_LIBS, if "gmodule" or 
+ dnl gthread is specified in MODULES, pass to glib-config
+ dnl
+-AC_DEFUN(AM_PATH_GLIB,
++AC_DEFUN([AM_PATH_GLIB],
+ [dnl 
+ dnl Get the cflags and libraries from the glib-config script
+ dnl
+@@ -18,43 +18,33 @@
+ 
+   if test x$glib_config_exec_prefix != x ; then
+      glib_config_args="$glib_config_args --exec-prefix=$glib_config_exec_prefix"
+-     if test x${GLIB_CONFIG+set} != xset ; then
+-        GLIB_CONFIG=$glib_config_exec_prefix/bin/glib-config
+-     fi
+   fi
+   if test x$glib_config_prefix != x ; then
+      glib_config_args="$glib_config_args --prefix=$glib_config_prefix"
+-     if test x${GLIB_CONFIG+set} != xset ; then
+-        GLIB_CONFIG=$glib_config_prefix/bin/glib-config
+-     fi
+   fi
+ 
+-  for module in . $4
++  for module in glib $4
+   do
+       case "$module" in
+-         gmodule) 
+-             glib_config_args="$glib_config_args gmodule"
+-         ;;
+-         gthread) 
+-             glib_config_args="$glib_config_args gthread"
++         glib|gmodule|gthread) 
++             glib_config_args="$glib_config_args $module"
+          ;;
+       esac
+   done
+ 
+-  AC_PATH_PROG(GLIB_CONFIG, glib-config, no)
+   min_glib_version=ifelse([$1], ,0.99.7,$1)
+   AC_MSG_CHECKING(for GLIB - version >= $min_glib_version)
+   no_glib=""
+-  if test "$GLIB_CONFIG" = "no" ; then
++  if test "" = "no" ; then
+     no_glib=yes
+   else
+-    GLIB_CFLAGS=`$GLIB_CONFIG $glib_config_args --cflags`
+-    GLIB_LIBS=`$GLIB_CONFIG $glib_config_args --libs`
+-    glib_config_major_version=`$GLIB_CONFIG $glib_config_args --version | \
++    GLIB_CFLAGS=`pkg-config --cflags $glib_config_args`
++    GLIB_LIBS=`pkg-config --libs $glib_config_args`
++    glib_config_major_version=`pkg-config --modversion glib | \
+            sed 's/\([[0-9]]*\).\([[0-9]]*\).\([[0-9]]*\)/\1/'`
+-    glib_config_minor_version=`$GLIB_CONFIG $glib_config_args --version | \
++    glib_config_minor_version=`pkg-config --modversion glib | \
+            sed 's/\([[0-9]]*\).\([[0-9]]*\).\([[0-9]]*\)/\2/'`
+-    glib_config_micro_version=`$GLIB_CONFIG $glib_config_args --version | \
++    glib_config_micro_version=`pkg-config --modversion glib | \
+            sed 's/\([[0-9]]*\).\([[0-9]]*\).\([[0-9]]*\)/\3/'`
+     if test "x$enable_glibtest" = "xyes" ; then
+       ac_save_CFLAGS="$CFLAGS"
+@@ -66,7 +56,7 @@
+ dnl checks the results of glib-config to some extent
+ dnl
+       rm -f conf.glibtest
+-      AC_TRY_RUN([
++      AC_RUN_IFELSE([AC_LANG_SOURCE([[
+ #include <glib.h>
+ #include <stdio.h>
+ #include <stdlib.h>
+@@ -138,7 +128,7 @@
+     }
+   return 1;
+ }
+-],, no_glib=yes,[echo $ac_n "cross compiling; assumed OK... $ac_c"])
++]])],, no_glib=yes,[echo $ac_n "cross compiling; assumed OK... $ac_c"])
+        CFLAGS="$ac_save_CFLAGS"
+        LIBS="$ac_save_LIBS"
+      fi
+@@ -160,10 +150,10 @@
+           echo "*** Could not run GLIB test program, checking why..."
+           CFLAGS="$CFLAGS $GLIB_CFLAGS"
+           LIBS="$LIBS $GLIB_LIBS"
+-          AC_TRY_LINK([
++          AC_LINK_IFELSE([AC_LANG_PROGRAM([[
+ #include <glib.h>
+ #include <stdio.h>
+-],      [ return ((glib_major_version) || (glib_minor_version) || (glib_micro_version)); ],
++]],     [[ return ((glib_major_version) || (glib_minor_version) || (glib_micro_version)); ]])],
+         [ echo "*** The test program compiled, but did not run. This usually means"
+           echo "*** that the run-time linker is not finding GLIB or finding the wrong"
+           echo "*** version of GLIB. If it is not finding GLIB, you'll need to set your"
